# Generated by Django 2.0.1 on 2018-01-24 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_challenge_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='challenge_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
