# Generated by Django 2.0.1 on 2018-01-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20180123_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_week_in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
